# Generated by Django 3.2.6 on 2024-10-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('cuenta', models.IntegerField(max_length=1000000)),
                ('direccion', models.CharField(max_length=30)),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
