# Generated by Django 3.2.6 on 2024-10-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='cuenta',
            field=models.IntegerField(),
        ),
    ]
