# Generated by Django 4.2.16 on 2024-11-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0002_alter_colegio_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='correo',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
    ]
