# Generated by Django 4.2.16 on 2024-11-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_alter_estudiante_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='correo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
