# Generated by Django 2.1.5 on 2024-11-15 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0004_estudiante_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='id',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='codigo',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='colegio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='colegio.Colegio'),
        ),
    ]
