# Generated by Django 2.1.5 on 2024-12-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0005_auto_20241115_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='codigo',
            new_name='id',
        ),
    ]
