# Generated by Django 3.2.6 on 2024-12-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estudiante', models.IntegerField(default=None)),
                ('saldo', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta_origen', models.CharField(max_length=15)),
                ('cuenta_destino', models.CharField(max_length=15)),
            ],
        ),
    ]
