# Generated by Django 3.2.6 on 2024-10-04 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta_origen', models.CharField(max_length=15)),
                ('cuenta_destino', models.CharField(max_length=15)),
                ('estudiante', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
            ],
        ),
    ]
