# Generated by Django 3.2.6 on 2024-10-19 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturas', '0002_alter_factura_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('direccion', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=20)),
                ('factura', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='facturas.factura')),
            ],
        ),
    ]
