# Generated by Django 3.2.6 on 2024-10-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
