# Generated by Django 2.1.5 on 2024-12-05 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_alter_factura_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estudiante',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante', to_field='codigo'),
        ),
    ]
