# Generated by Django 2.1.5 on 2024-12-05 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_auto_20241205_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estudiante',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante'),
        ),
    ]
